Application: 
    Name:
    Release: 
    Target: Development
Hosts:
    Development: 
        - localhost
    Staging: 
        - staging.sfpl.io
        - localhost
Content: 
User:
    Session:
        Timeout: 3600000
Cookies:
    Names:
        COOKIE_VISITOR: vid
        COOKIE_SESSION: sid
        COOKIE_USER: uid
        COOKIE_AUTH: jwt
        COOKIE_LAST_ACTIVE: la
        COOKIE_REFERRAL: ref
        COOKIE_EXPERIMENT: x
        COOKIE_EXP_PARAMS: xp
        COOKIE_QPS: qps
        COOKIE_CONSENT: CookieConsent
        COOKIE_EMAIL_HASH: ehash
Routes:
    "/settings":
        Regex: /settings
        PageType: settings
Tracker:
    Track: true
    ApiVersion: v1
    WebSocket: true
    WS:
        Development: ws://localhost:8880/tr/v1/ws
        Staging: ws://tr.sfpl.io/tr/v1/ws
        Production: wss://tr.sfpl.io/tr/v1/ws
    Url: 
        Development: http://localhost:8880
        Staging: https://tr.sfpl.io
        Production: https://tr.sfpl.io
Styles: |-
    .black { color: black; }

